import SwiftUI

struct CompDetailView: View {
    let comp: TFTComp
    var siblings: [TFTComp] = []
    var body: some View {
        ZStack {
            TFTTheme.background.ignoresSafeArea()
            ScrollView { VStack(alignment: .leading, spacing: 16) { titleBlock; if !siblings.isEmpty { siblingsBlock }; earlyBlock; itemBlock; notesBlock }.padding(14).padding(.bottom, 24) }
        }
        .navigationTitle(comp.title)
        .navigationBarTitleDisplayMode(.inline)
    }
    private var titleBlock: some View { VStack(alignment: .leading, spacing: 10) { HStack { Text(comp.tier).font(.title3.bold()).foregroundColor(.black).frame(width: 42, height: 42).background(TFTTheme.tierColor(comp.tier)).cornerRadius(10); VStack(alignment: .leading, spacing: 3) { Text(comp.title).font(.title3.bold()).foregroundColor(.white); Text(comp.subtitle + " · " + comp.sourceRanks.joined(separator: " / ")).font(.caption).foregroundColor(TFTTheme.text2) }; Spacer() }; HStack(spacing: 0) { StatCell(value: String(format: "%.2f", comp.avgPlace), label: "Place", accent: TFTTheme.green); StatCell(value: String(format: "%.2f", comp.playRate), label: "Play Rate", accent: .white); StatCell(value: String(format: "%.1f%%", comp.top4), label: "Top 4", accent: TFTTheme.green); StatCell(value: String(format: "%.1f%%", comp.winRate), label: "Win %", accent: TFTTheme.goldSoft) } }.padding(14).background(TFTTheme.panel).cornerRadius(16) }
    private var siblingsBlock: some View { VStack(alignment: .leading, spacing: 10) { Text("BIẾN THỂ CÙNG HỌ").font(.caption.bold()).foregroundColor(TFTTheme.goldSoft); ForEach(siblings) { sibling in NavigationLink(destination: CompDetailView(comp: sibling, siblings: siblings.filter { $0.id != sibling.id } + [comp])) { CompRow(rank: nil, comp: sibling, variantCount: 0, compact: true) }.buttonStyle(PlainButtonStyle()) } }.padding(12).background(TFTTheme.panel).cornerRadius(16) }
    private var earlyBlock: some View { VStack(alignment: .leading, spacing: 10) { Text("TÙY CHỌN & BẮT ĐẦU").font(.caption.bold()).foregroundColor(TFTTheme.goldSoft); ForEach([4,5,6,7], id: \.self) { level in HStack(spacing: 9) { Text("Cấp \(level)").font(.caption.weight(.semibold)).foregroundColor(.white).frame(width: 44).padding(.vertical, 8).background(TFTTheme.panel2).cornerRadius(7); ScrollView(.horizontal, showsIndicators: false) { HStack(spacing: 6) { ForEach(Array(comp.units.prefix(min(level, comp.units.count)))) { unit in VStack(spacing: 3) { RemoteImage(url: unit.imageURL, cornerRadius: 5).frame(width: 38, height: 38); Text(unit.name).font(.system(size: 7.5)).foregroundColor(TFTTheme.text2).lineLimit(1).frame(width: 42) } } } } }.padding(.vertical, 3) }; Text("Khung Cấp 4–7 là gợi ý do app dựng từ đội hình cuối để dễ xem, không phải positioning gốc của tactics.tools.").font(.caption2).foregroundColor(TFTTheme.text2) }.padding(12).background(TFTTheme.panel).cornerRadius(16) }
    private var itemBlock: some View { VStack(alignment: .leading, spacing: 12) { Text("TRANG BỊ ƯU TIÊN").font(.caption.bold()).foregroundColor(TFTTheme.goldSoft); ForEach(comp.units.filter { !$0.items.isEmpty }) { unit in HStack(spacing: 10) { RemoteImage(url: unit.imageURL, cornerRadius: 8).frame(width: 48, height: 48); VStack(alignment: .leading, spacing: 6) { Text(unit.name).font(.subheadline.bold()).foregroundColor(.white); ScrollView(.horizontal, showsIndicators: false) { HStack(spacing: 8) { ForEach(unit.items) { item in HStack(spacing: 5) { RemoteImage(url: item.imageURL, cornerRadius: 4).frame(width: 28, height: 28); Text(item.name).font(.caption2).foregroundColor(.white.opacity(0.78)) } } } } }; Spacer() }.padding(10).background(TFTTheme.panel2.opacity(0.75)).cornerRadius(12) } }.padding(12).background(TFTTheme.panel).cornerRadius(16) }
    private var notesBlock: some View { VStack(alignment: .leading, spacing: 9) { Text("GỢI Ý CHƠI").font(.caption.bold()).foregroundColor(TFTTheme.goldSoft); ForEach(comp.notes, id: \.self) { note in HStack(alignment: .top, spacing: 8) { Circle().fill(TFTTheme.goldSoft).frame(width: 6, height: 6).padding(.top, 6); Text(note).font(.footnote).foregroundColor(.white.opacity(0.82)) } } }.padding(14).background(TFTTheme.panel).cornerRadius(16) }
}
